[build]
  publish = "frontend/build"
  command = "cd frontend && yarn install && yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
